# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d3fc5fe307c60f0701352a461f80ac83250557cb61b9240634a44669c2ffd5befe72ddbb543451f9cc45c02d40c314a18ee0b59918ecc90a758935498f07b8fe

test:
  secret_key_base: 67d9b0fda962a1d55dc3a902856b34c72be8d0a8cf69432547c175a0c30253943fe8384983f7f4384f5f010a7fbaf5c8a039d3a1917f2d562c11b5b1afcb6682

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
